"""Stable language and voice catalogs exposed to the desktop UI."""

POPULAR_TARGET_LANGUAGES = [
    ("vi", "Vietnamese", "Tiếng Việt"),
    ("en", "English", "English"),
    ("zh", "Chinese", "中文"),
]


OMNIVOICE_TTS_VOICES = [
    ("omnivoice:female", "Natural female", "natural"),
    ("omnivoice:male", "Natural male", "natural"),
    ("omnivoice:female_low", "Warm female", "natural"),
    ("omnivoice:deep", "Deep male", "natural"),
    ("omnivoice:bright", "Bright female", "natural"),
    ("omnivoice:male_high", "Bright male", "natural"),
    ("omnivoice:female_mature", "Mature female", "natural"),
    ("omnivoice:male_mature", "Mature male", "natural"),
    ("omnivoice:female_soprano", "Clear high female", "natural"),
    ("omnivoice:male_tenor", "Clear high male", "natural"),
    ("omnivoice:female_narrator", "Female narrator", "narration"),
    ("omnivoice:male_narrator", "Male narrator", "narration"),
    ("omnivoice:female_elder_high", "Lively elder female", "narration"),
    ("omnivoice:male_elder_high", "Lively elder male", "narration"),
    ("omnivoice:elder", "Elder narrator", "narration"),
    ("omnivoice:storyteller", "Deep storyteller", "narration"),
    ("omnivoice:whisper", "Soft whisper", "style"),
    ("omnivoice:whisper_low", "Deep whisper", "style"),
    ("omnivoice:whisper_high", "Bright whisper", "style"),
    ("omnivoice:whisper_elder", "Elder whisper", "style"),
    ("omnivoice:child", "Young voice", "style"),
    ("omnivoice:cartoon", "Cartoon voice", "style"),
    ("omnivoice:child_soft", "Soft child", "style"),
    ("omnivoice:child_low", "Low child voice", "style"),
    ("omnivoice:animated_bright", "Bright animation", "entertainment"),
    ("omnivoice:animated_soft", "Soft animation", "entertainment"),
    ("omnivoice:comic_low", "Low comic", "entertainment"),
    ("omnivoice:tech_presenter", "Tech presenter", "entertainment"),
    ("omnivoice:show_host", "Show host", "entertainment"),
    ("omnivoice:trailer_deep", "Deep trailer", "entertainment"),
    ("omnivoice:radio_warm", "Warm radio", "entertainment"),
    ("omnivoice:mystery_whisper", "Mystery whisper", "entertainment"),
    ("omnivoice:female_gentle", "Gentle female", "natural"),
    ("omnivoice:male_soft", "Soft male", "natural"),
    ("omnivoice:female_confident", "Confident female", "narration"),
    ("omnivoice:male_broadcast", "Broadcast male", "narration"),
    ("omnivoice:child_bright", "Bright child", "style"),
    ("omnivoice:elder_warm", "Warm elder", "style"),
    ("omnivoice:comic_high", "High comic", "entertainment"),
    ("omnivoice:documentary", "Documentary", "entertainment"),
]
